export const links={
    base:"/",
    home:"/",
    about:"/about",
    contact:{
        base:"/contact",
    create:"/contact/create",
    delete:"/contact/delete",
    edit:"/contact/edit",
    upate:"/contact/edit",
    list:"/contact/users",
    show:"/contact/user",
    view:"/contact/users",
    users:"/contact/users",
}
    ,
    login:"/login",
    register:"/register",
    logout:"/logout",
    dashboard:"/dashboard",
    profile:"/profile",
    charts:"/chart",
}